language: java
sudo: false
install: true

addons:
  sonarqube:
    token:
      secure: tZWPobcg+n+vpwKrTD4ztfat4CNynqE/mQcFx9SLpYsZVdXHYP6qt46hKud+WtDBFN27VmflnBVgyTJJUbtFUOO2M/prFLyeV7n6uE8bGIkrjSUzXXy1Eh5uVmMkhgC1roOjQLEpYkBg4Cj0M88taIxGtZbKae3p5O8GVw6OI8qtsAG3Twj1YrbWCltiH3RW8Jj8W1JFooL9ho8aNrvqOtDosTa4SW/utuHsNUXhy0GCMaqunm9s4017Cf3s/8dFO74RR+nUlZYQxy/zYOtksab6wN0mvlienJSkXXAdIovgTWE07l35mqj6wRgrolvOtBuJtBI/NGkn6PsE3KfVudkzlFKg+3DTOpbmsfmRHGl8bN8aezR8DczlrrHH3seZkeur8UXVDAN4UNFK1NagxO13Ctbwa7BL+zQegGSk6uRkMglsN++aSi7N3X1fnWcQG3eXxpXdRLq5v5uw7j52g+PratBXB3p/zCpQUqCE8o3ndmClklKyAPAtO/fL3CVTIhBEmLbUnG8Sa+Zou4x0wP1PMbI8A8hT/6kzddm26AYUPxnb5GgdFid7M3ibBLozKk/zcAxo7GLNTwlPjJ/XeN0EBfc4joOGCzh4DYqj1mLVjHda5WtzP6jJIwX+7sIfjhGQnOM0dr8FKwc4NrP8vRkGNl1IZ6pHNXuVhvumtok=

script:
- mvn clean verify coveralls:report install sonar:sonar
jdk:
- oraclejdk8

deploy:
  provider: heroku
  app: rocketvoip
  api_key:
    secure: h+9pverv7p9f89bbPmv7WB4qtxzqGCUhssRNIFv8J+7WdVkkT72YipcPmM7AJfNJOVtqji+DnGJ9v+zBKx0nIuCDFV5C16Ex/unUe1mEzQkogfrKVPf8aGZiDRUYmJA5Y64xeZLZl4dTLv9XozU3nYo25wqw9gA3KyH6CaFKQCOdF1MgZR98wnMayHZqMN5jK7Ainz04ffxpiLclmPmTQkuKuStgTSba5xgjjHu5as33f8Vr3OO5PTz5+J2uyNK/E2cHzN3qfPzDYMuw9FkB6HWkfNqMKowfN1MGd606jajmrJv6Tqj+Tlyi3FRq+qwzQiNWOGG6SDxrLfww/7yIat+mGrbAEoGq2bDXVYXnSaH9R/S3Tw+Ds8OPLX/4NlhKokp+bIfWnCKUb2T0ar7k95Zgg/7f7rJIpqPdsGUtsVmUoDDlXg8n/eF7PjBstj6/jsRzHbWPpu9YUizAS+9k1+3uKp6h7oGW7YRhS6x3WYMxp4VZzkiw3QBy5x/D0jvj8a/JBAyeD7EiLgakKVbViPq3tE8yrnmes/rzGJ7R403mAt6cxxZFpjI1YtPapCb5pvOAAawOfYpo7DLma/1iwxsxbOSltc/sKH1kqKUmu58f4w0Kw1m4LVxEpZIe/uK5NB/zTCL1EUiLi+ZX9XYlFJ+TwOTBzkaF9ybszYPcOb4=

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'